### ISSUE TITLE
App gone in PlayStore

### ISSUE THREAD

**Issue by oholika** [MetalMatze/Krautreporter#7]
The Link is dead: 
https://play.google.com/store/apps/details?id=de.metalmatze.krautreporter

**Comment by metalmatze** [comment]
You're right. I got a mail from Google on Saturday.

> REASON FOR SUSPENSION:Violation of the impersonation or deceptive behavior provisions of the Content Policy. Please refer to the impersonation policy help article for more information.

Seems like they think I just used the Krautreporter logo and stuff without their permission. 

I'm working with Krautreporter to get it fixed.

**Comment by JohannesWSchmidt** [comment]
@MetalMatze Do you have anything to do with the Google Play Kiosk app? It appeared today: https://play.google.com/store/newsstand/news/Krautreporter?id=CAow2eKfCQ

**Comment by metalmatze** [comment]
Nope, that's none of my business. It is there acutally quite a long time. Either Google does that automatically or someone from Krautreporter publishes there. But not me.

I've spoken to a member from Krautreporter just yet. Hopefully I can prove to Google that I have the rights, by the end of the week.

**Comment by metalmatze** [comment]
Yesterday Google mailed me saying that my App is being reinstated.
I've uploaded a new apk with a new versionCode. It should appear now within the next hours.

https://play.google.com/store/apps/details?id=de.metalmatze.krautreporter
